name: Interrogate Documentation

on: [pull_request, workflow_dispatch]
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v3.1.0
      with:
        python-version: 3.8

    - name: Python Interrogate Check
      uses: gavingosling/python-interrogate-check@main
      with:
        path: './'
        badge-location: 'badges/interrogate_badge.svg'
        fail-under: 0

    - name: Set Env
      run: echo "TABLE=$(cat badges/table.txt)" >> $GITHUB_ENV

    - name: Comment PR
      if: ${{ github.event_name == 'pull_request' }}
      uses: thollander/actions-comment-pull-request@master
      with:
        message: 'Example of message !'
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
