

name: envtest

on:
  workflow_dispatch:
  repository_dispatch:
    types: [start-workflow]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Branch name
        run: |
          STR="BRANCH=branch-${GITHUB_REF##*/}"
          echo $STR >> $GITHUB_ENV
      - name: a
        run: echo a



