
name: push-to-gcp

on:
  repository_dispatch:
    types: [start-workflow]
    
jobs:
  build:
    permissions:
      contents: 'read'
      id-token: 'write'
      
    runs-on: ubuntu-latest
    steps:
    # Checkout code
    - name: Checkout
      uses: actions/checkout@v2
    
    # Install Gcloud
    - name: Configure Gcloud
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    # Configure Workload Identity Federation via a credentials file.
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0.3.1'
      with:
        create_credentials_file: 'true'
        workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY }}
        service_account: ${{ secrets.SERVICE_ACCOUNT }}
        
    - run: |
        gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
        gcloud info
    #    gcloud auth configure-docker
    #    docker pull busybox
    #    docker tag busybox gcr.io/${{ secrets.GCP_PROJECT_ID}}/test/busybox
    #    docker push gcr.io/${{ secrets.GCP_PROJECT_ID}}/test/busybox
